# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# just to make sure this is my pipeline
trigger:
- master

pool:
  name: 'ubuntu-latest'
  demands:
  - Agent.OS -equals Linux
  - Agent.Name -equals VSTS-02

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


